---
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile.ci
    image: wb-zero-app-ci
    volumes:
      - .:/code:ro
    env_file:
      - ./.env.example
    environment:
      - POSTGRES_HOST=db
      - STAN_HOST=stan
    depends_on:
      - db
      - stan

  db:
    image: postgres:14-alpine
    volumes:
      - ./initdb/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./initdb/create_template_db.sh:/docker-entrypoint-initdb.d/create_template_db.sh
    tmpfs:
      - /var/lib/postgresql/data
    env_file:
      - ./.env.example

  stan:
    image: nats-streaming:0.24-alpine
